Rahul:
  SocialConnect:
    facebook:
      appid: 'xxxxxxxxxxx' #Enter Your Facebook App ID.visit deveoper.facebook.com
      secret: 'xxxxxxxxxxxxxxxxxxxxxxxx' #app secret
      user: 'xxxxxxxxxxxxxxxx' # the profile / page you want to post on
      link: 'neos.demo' #The link to your website
      caption: 'some caption' #default caption for the link
      name: 'Neos Demo' #Title for the post
      desc: 'This is a test blog to test the SocialConnect feature for Neos' #Description for the post
      image: 'http://www.cms2cms.com/wp-content/uploads/2013/05/typo3logo.jpg' #Default URL to the image
      ##Get the access token at https://developers.facebook.com/tools/explorer/?method=GET&path=me%3Ffields%3Did%2Cname
      token: 'xxxxxxxxxxx'
    twitter: #visit https://apps.twitter.com/app/<your app id >/keys
      apiKey: 'xxxxxxxxxxxxxxxxxxxx' # API Key 
      apiSecret: 'xxxxxxxxxxxxxxxx' #API Secret
      token: 'xxxxxxxxx-xxxxxxxxxxxxx' #Access Token 
      tokenSecret: 'xxxxxxxxxxxxxxxxxxxx' #Acess token secret
      link: 'neos.demo' #The base address to your website
      image: '' #URL to the image
    blogger:
      username: 'xxxxxxxxxxx' #google user name
      password: 'zzzzzzzzzzzzzz' #google password
      blogname: 'xxxxxxxxxxx' #name of the blog
  
TYPO3:
  Flow:
    object:
      excludeClasses:
        'zend.*': ['.*']
  Neos:
    userInterface:
      editPreviewModes:
        facebookPreview:
          isEditingMode: FALSE
          isPreviewMode: TRUE
          typoScriptRenderingPath: 'facebookPreview'
          title: 'Facebook Preview'
          position: 100
        twitterPreview:
          isEditingMode: FALSE
          isPreviewMode: TRUE
          typoScriptRenderingPath: 'twitterPreview'
          title: 'Twitter Preview'
          position: 100