Rahul:
  SocialConnect:
    facebook:
      appid: 'XXXXXXXXXXXXX' #Enter Your Facebook App ID.visit deveoper.facebook.com
      secret: 'XXXXXXXXXXXXXX' #app secret
      user: '222584177830048' # the profile / page you want to post on
      link: 'www.example.com' #The link to your website
      caption: 'some caption' #caption for the link
      name: 'some name' #Title for the post
      desc: 'some desc' #Description for the post
      image: 'XXXXXXXXXXXX' #URL to the image
      ##Get the access token at https://developers.facebook.com/tools/explorer/?method=GET&path=me%3Ffields%3Did%2Cname
      token: 'XXXXXXXXXXXXXX'