Rahul:
  SocialConnect:
    facebook:
      appid: '' #Enter Your Facebook App ID.visit deveoper.facebook.com
      secret: '' #app secret
      user: 'me' # the profile / page you want to post on
      link: '' #The link to your website
      ##Get the access token at https://developers.facebook.com/tools/explorer/?method=GET&path=me%3Ffields%3Did%2Cname
      token: ''
